st_app:
    resource: "@STAppBundle/Controller/TrickController.php"
    type: annotation
    prefix:   /

st_app_group:
    resource: "@STAppBundle/Controller/CategoryController.php"
    type: annotation
    prefix:   /category

st_app_comment:
    resource: "@STAppBundle/Controller/CommentController.php"
    type: annotation
    prefix:   /comment

st_app_image:
    resource: "@STAppBundle/Controller/ImageController.php"
    type: annotation
    prefix:   /image

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
